# Generated by Django 4.2.2 on 2023-07-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keystroke",
            name="downtime",
        ),
        migrations.RemoveField(
            model_name="keystroke",
            name="uptime",
        ),
    ]
