# Generated by Django 4.2.2 on 2023-07-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_keystroke_downtime_remove_keystroke_uptime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keystroke",
            old_name="dwelltime",
            new_name="dwellTime",
        ),
        migrations.RenameField(
            model_name="keystroke",
            old_name="inter_key_latency",
            new_name="interKeyLatency",
        ),
    ]
