# Generated by Django 4.2.2 on 2023-07-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_dwelltime_keystroke_dwelltime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keystroke",
            name="key",
            field=models.IntegerField(max_length=1),
        ),
    ]
